name: Publish image

on:
  push:
    tags:
      - '*.*.*-beta.*'
      - '*.*.*-alpha.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: echo "Would test"

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Define release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{env.RELEASE_VERSION}}
          name: Release ${{ env.RELEASE_VERSION }}
          body: Automated Release
